### ISSUE TITLE
这种牌怎么上来让我拆王？？

### ISSUE THREAD

**Issue by DreamVoid** [tianqiraf/DouZero_For_HappyDouDiZhu#13]
![QQ图片20210722150907.png](https://i.loli.net/2021/07/22/FS6dqYsMcgbW7Rx.png)
![QQ图片20210722150900.png](https://i.loli.net/2021/07/22/ygzCf3wLd5plOiW.png)

虽说也有待提高吧，但是这实在让我无语

另外，为什么我打开的时候窗口显示的牌顺序和游戏里的是反向的？我看视频都是和游戏里的牌的顺序一样

**Comment by tianqiraf** [comment]
@DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序

**Comment by DreamVoid** [comment]
> @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序

但是第一手拆王这不就是送吗，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下

**Comment by LauchuAnren** [comment]
> 
> 
> > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> 
> 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下

你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？

**Comment by DreamVoid** [comment]
> > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > 
> > 
> > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> 
> 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？

是刚玩Github吗😅

**Comment by LauchuAnren** [comment]
> 
> 
> > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > 
> > > 
> > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > 
> > 
> > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> 
> 是刚玩Github吗😅 Joined GitHub this month

玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是

**Comment by tianqiraf** [comment]
没有注意到你这是不洗牌模式， 如@LauchuAnren 所说，这个模型是根据经典玩法训练出来的，不适用于不洗牌模式。猜测AI的思路是出掉小王留大王，再走四带二出完。

**Comment by LauchuAnren** [comment]
> 
> 
> > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > 
> > > 
> > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > 
> > 
> > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> 
> 是刚玩Github吗😅 Joined GitHub this month

流汗黄豆，有够低能的，多少沾点

**Comment by DreamVoid** [comment]
> > > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > > 
> > > > 
> > > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > > 
> > > 
> > > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> > 
> > 
> > 是刚玩Github吗😅 Joined GitHub this month
> 
> 玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是

小伙子也不知道是谁先点的踩呢
好好说话不会，上来就是一句找茬，你算什么东西😅
@tianqiraf Close discussion please.

**Comment by LauchuAnren** [comment]
> 
> 
> > > > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > > > 
> > > > > 
> > > > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > > > 
> > > > 
> > > > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> > > 
> > > 
> > > 是刚玩Github吗😅 Joined GitHub this month
> > 
> > 
> > 玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是
> 
> 小伙子也不知道是谁先点的踩呢
> 好好说话会不会，上来就是一句找茬，你算什么东西😅
> 
> @tianqiraf Lock conversation please.

谁先点踩谁没家人，怎么样

**Comment by DreamVoid** [comment]
> > > > > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > > > > 
> > > > > > 
> > > > > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > > > > 
> > > > > 
> > > > > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> > > > 
> > > > 
> > > > 是刚玩Github吗😅 Joined GitHub this month
> > > 
> > > 
> > > 玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是
> > 
> > 
> > 小伙子也不知道是谁先点的踩呢
> > 好好说话会不会，上来就是一句找茬，你算什么东西😅
> > @tianqiraf Lock conversation please.
> 
> 谁先点踩谁没家人，怎么样

你已经没有家人了，却来和我说谁先点踩谁没家人，自找无趣吗

**Comment by LauchuAnren** [comment]
> 
> 
> > > > > > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > > > > > 
> > > > > > > 
> > > > > > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > > > > > 
> > > > > > 
> > > > > > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> > > > > 
> > > > > 
> > > > > 是刚玩Github吗😅 Joined GitHub this month
> > > > 
> > > > 
> > > > 玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是
> > > 
> > > 
> > > 小伙子也不知道是谁先点的踩呢
> > > 好好说话会不会，上来就是一句找茬，你算什么东西😅
> > > @tianqiraf Lock conversation please.
> > 
> > 
> > 谁先点踩谁没家人，怎么样
> 
> 你已经没有家人了，却来和我说谁先点踩谁没家人，自找无趣吗

你说是，那就是。😁

**Comment by DreamVoid** [comment]
> > > > > > > > > @DreamVoid 这是以胜率为目标的模型，不会考虑炸弹加分的情况。GUI界面里的牌顺序是对的，控制台输出没有做排序
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 但是第一手拆王这不就是送吗，Ai最起码知道小王是单牌第二大、王炸最大的规则吧，而且这还是第一手出牌，我实在没法理解为什么这样出有90多的胜率，可否请大佬给我解释一下
> > > > > > > 
> > > > > > > 
> > > > > > > 你是来找茬的吧，这个模型是根据经典玩法训练出来的，你拿来跑不洗牌然后问为什么拆王？你这三炸牌能在经典场抓出来那就是天牌，拆王也是必赢的。AI给90胜率没啥问题吧？不洗牌里全是炸弹，你这就是很普通的牌，拆王肯定不好赢。你现在是不是又要开始怪AI不知道你玩的是什么模式了？
> > > > > > 
> > > > > > 
> > > > > > 是刚玩Github吗😅 Joined GitHub this month
> > > > > 
> > > > > 
> > > > > 玩尬的是吧。。几岁了兄弟，好歹说点啥反驳一下，没话找话这样不好吧。。喜欢点踩是吧，Github让你玩明白了属于是
> > > > 
> > > > 
> > > > 小伙子也不知道是谁先点的踩呢
> > > > 好好说话会不会，上来就是一句找茬，你算什么东西😅
> > > > @tianqiraf Lock conversation please.
> > > 
> > > 
> > > 谁先点踩谁没家人，怎么样
> > 
> > 
> > 你已经没有家人了，却来和我说谁先点踩谁没家人，自找无趣吗
> 
> 你说是，那就是。😁

你终于承认了😅
