### ISSUE TITLE
开始以后闪退

### ISSUE THREAD

**Issue by 0xbba** [tianqiraf/DouZero_For_HappyDouDiZhu#23]
看记录好像能识别出手牌，麻烦帮忙看看是为什么

> F:\Desktop\DouZero_For_HappyDouDiZhu-2.0>python main.py
> {'three_landlord_cards': [9, 8, 3], 'landlord_up': [17, 17, 14, 14, 13, 13, 12, 12, 10, 9, 8, 7, 7, 6, 5, 4, 3], 'landlord': [9, 9, 9, 10, 10, 10, 11, 11, 11, 11, 12, 12, 13, 13, 14, 14, 17, 17, 20, 30], 'landlord_down': [3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 8, 8, 8]}
> Traceback (most recent call last):
>   File "C:\Users\liule\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 83, in <module>
>     refresh()
>   File "C:\Users\liule\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 73, in refresh
>     if not Git.refresh(path=path):
>   File "C:\Users\liule\AppData\Local\Programs\Python\Python38\lib\site-packages\git\cmd.py", line 287, in refresh
>     raise ImportError(err)
> ImportError: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 164, in init_cards
>     ai_players[1] = DeepAgent(self.user_position, self.card_play_model_path_dict[self.user_position])
>   File "F:\Desktop\DouZero_For_HappyDouDiZhu-2.0\douzero\evaluation\deep_agent.py", line 25, in __init__
>     self.model = _load_model(position, model_path)
>   File "F:\Desktop\DouZero_For_HappyDouDiZhu-2.0\douzero\evaluation\deep_agent.py", line 7, in _load_model
>     from douzero.dmc.models import model_dict
>   File "F:\Desktop\DouZero_For_HappyDouDiZhu-2.0\douzero\dmc\__init__.py", line 1, in <module>
>     from .dmc import train
>   File "F:\Desktop\DouZero_For_HappyDouDiZhu-2.0\douzero\dmc\dmc.py", line 12, in <module>
>     from .file_writer import FileWriter
>   File "F:\Desktop\DouZero_For_HappyDouDiZhu-2.0\douzero\dmc\file_writer.py", line 25, in <module>
>     import git
>   File "C:\Users\liule\AppData\Local\Programs\Python\Python38\lib\site-packages\git\__init__.py", line 85, in <module>
>     raise ImportError('Failed to initialize: {0}'.format(exc))
> ImportError: Failed to initialize: Bad git executable.
> The git executable must be specified in one of the following ways:
>     - be included in your $PATH
>     - be set via $GIT_PYTHON_GIT_EXECUTABLE
>     - explicitly set via git.refresh()
> 
> All git commands will error until this is rectified.
> 
> This initial warning can be silenced or aggravated in the future by setting the
> $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
>     - quiet|q|silence|s|none|n|0: for no warning or exception
>     - warn|w|warning|1: for a printed warning
>     - error|e|raise|r|2: for a raised exception
> 
> Example:
>     export GIT_PYTHON_REFRESH=quiet

**Comment by 0xbba** [comment]
pos_debug.py也运行不了

> F:\Desktop\DouZero_For_HappyDouDiZhu-2.0>python pos_debug.py
> Traceback (most recent call last):
>   File "pos_debug.py", line 25, in <module>
>     cv2.imshow("test", img)
> cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
>

**Comment by tianqiraf** [comment]
@0xbba  克隆一下最新的代码，main.py第347行有os.environ["GIT_PYTHON_REFRESH"] = 'quiet'
pos_debug.py需要替换自己的截图路径

**Comment by 0xbba** [comment]
> @0xbba 克隆一下最新的代码，main.py第347行有os.environ["GIT_PYTHON_REFRESH"] = 'quiet'
> pos_debug.py需要替换自己的截图路径

已解决,感谢.我直接在Releases下载的,没想到不是最新的
